### PR TITLE
Fix #1

### LINKED ISSUE #1: Suggestions for a better footer
I have an issue (1) and some suggestions (2, 3 and 4) for a better footer:

1. use `\insertshortauthor` instead of `\insertauthor` in https://github.com/electricant/beamerThemePadovaDEI/blob/056fdfffbddbc859119aab0ecc62cd05654776c2/beamerouterthemePadovaDEI.sty#L79  
in this way users can set an optional shortauthor text in title definition (see [Beamer guide](http://ctan.mirror.garr.it/mirrors/CTAN/macros/latex/contrib/beamer/doc/beameruserguide.pdf), page 65).
2. use `/` instead of `of` for better internationalization in https://github.com/electricant/beamerThemePadovaDEI/blob/056fdfffbddbc859119aab0ecc62cd05654776c2/beamerouterthemePadovaDEI.sty#L75
3. Add the title: 
```
\pgftext[top,at=\pgfpoint{0.5\paperwidth}{0.025\paperwidth}]{
    \usebeamerfont{frame number in foot}
    \usebeamercolor[fg]{frame number in foot}\insertshorttitle 
  }
```
4. Adjust the footer text alignment: in 4:3 `0.025\paperwidth` is correct, but in 16:9 it will be better `0.020\paperwidth`.

### PR DESCRIPTION
**Pull request by DPDmancul**
Fixes #1

### CODE REVIEW

**Comment by electricant** [comment]
Thanks. I tried to merge your changes into the 'devel' branch, to see how they look like in a sample presentation.

I do not see any change however. Could you please double check? Maybe it's an issue with my setup.

**Comment by DPDmancul** [comment]
> Thanks. I tried to merge your changes into the 'devel' branch, to see how they look like in a sample presentation.
> 
> I do not see any change however. Could you please double check? Maybe it's an issue with my setup.

Yes it loads the installed package: try putting all the files in the same folder, for me it works.
Then I suggest to add the optional short author to avoid overlap between author and title in footer: `\author[Trackers, Guy & Co.]{Bear Trackers, That Guy and Cool People}`

**Comment by electricant** [comment]
Sorry I messed up the commits within the two branches. Now it should be fixed. Have a look.
I still don't get latex to update the theme for some reason. Could you provide the updated sample presentation as compiled by your setup?
I'll add it to the repo and merge your PR into master. Thanks again

**Comment by DPDmancul** [comment]
The problem is that `\usepackage{../beamerthemePadovaDEI}` for some (unknown to me) reasons brings the package from the texmf folder: to use a local package you must put the test file and the package files in the same folder and recall the package by `\usepackage{beamerthemePadovaDEI}`

**Comment by DPDmancul** [comment]
I uploaded the resulting file here: https://github.com/DPDmancul/beamerThemePadovaDEI/blob/master/sample/sample_presentation.pdf
I tried a new pull request but maybe there are some problems on the GitHub servers, because it gives me always error 500.

**Comment by electricant** [comment]
Now I fixed it. Merged into master. Thanks for the contribution! :)

**Pull request closed without merging**
